"""empty message

Revision ID: 5467501174e6
Revises: 78abee01eb83
Create Date: 2019-06-20 23:55:06.780701

"""

# revision identifiers, used by Alembic.
revision = '5467501174e6'
down_revision = '78abee01eb83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
