"""empty message

Revision ID: e9a6740d5749
Revises: 5467501174e6
Create Date: 2019-06-21 08:05:01.509805

"""

# revision identifiers, used by Alembic.
revision = 'e9a6740d5749'
down_revision = '5467501174e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('genre', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('affiche', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('notation',
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['movie.name'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notation')
    op.drop_table('movie')
    # ### end Alembic commands ###
